/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mouseandlistevent;

import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.PointerInfo;

/**
 *
 * @author green
 */
public class ExerMouseEvent extends javax.swing.JFrame {

    /**
     * Creates new form ExerMouseEvent
     */
    public ExerMouseEvent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coloredPnl = new javax.swing.JPanel();
        displayLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        coloredPnl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                coloredPnlMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                coloredPnlMouseMoved(evt);
            }
        });
        coloredPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coloredPnlMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                coloredPnlMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                coloredPnlMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                coloredPnlMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout coloredPnlLayout = new javax.swing.GroupLayout(coloredPnl);
        coloredPnl.setLayout(coloredPnlLayout);
        coloredPnlLayout.setHorizontalGroup(
            coloredPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        coloredPnlLayout.setVerticalGroup(
            coloredPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );

        displayLbl.setText("   ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coloredPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(coloredPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void coloredPnlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coloredPnlMouseExited
        // TODO add your handling code here:
        coloredPnl.setBackground(Color.white);
        displayLbl.setText("mouse is outside JPanel");
    }//GEN-LAST:event_coloredPnlMouseExited

    private void coloredPnlMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coloredPnlMouseMoved
        // TODO add your handling code here:
        coloredPnl.setBackground(Color.green);
        PointerInfo info=MouseInfo.getPointerInfo();
        Point loc= info.getLocation();
        displayLbl.setText("Moved at ["+ (int )loc.getX()+" , "+ (int )loc.getY()+"]");
    }//GEN-LAST:event_coloredPnlMouseMoved

    private void coloredPnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coloredPnlMouseClicked
        // TODO add your handling code here:
        coloredPnl.setBackground(Color.green);
        PointerInfo info=MouseInfo.getPointerInfo();
        Point loc= info.getLocation();
        displayLbl.setText("clicked at ["+ (int )loc.getX()+" , "+ (int )loc.getY()+"]");
    }//GEN-LAST:event_coloredPnlMouseClicked

    private void coloredPnlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coloredPnlMousePressed
        // TODO add your handling code here:
        coloredPnl.setBackground(Color.green);
        PointerInfo info=MouseInfo.getPointerInfo();
        Point loc= info.getLocation();
        displayLbl.setText("Pressed at ["+ (int )loc.getX()+" , "+ (int )loc.getY()+"]");
    }//GEN-LAST:event_coloredPnlMousePressed

    private void coloredPnlMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coloredPnlMouseDragged
        // TODO add your handling code here:
        coloredPnl.setBackground(Color.green);
        PointerInfo info=MouseInfo.getPointerInfo();
        Point loc= info.getLocation();
        displayLbl.setText("Dragged at ["+ (int )loc.getX()+" , "+ (int )loc.getY()+"]");
    }//GEN-LAST:event_coloredPnlMouseDragged

    private void coloredPnlMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coloredPnlMouseReleased
        // TODO add your handling code here:
        coloredPnl.setBackground(Color.green);
        PointerInfo info=MouseInfo.getPointerInfo();
        Point loc= info.getLocation();
        displayLbl.setText("Released at ["+ (int )loc.getX()+" , "+ (int )loc.getY()+"]");
    }//GEN-LAST:event_coloredPnlMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExerMouseEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExerMouseEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExerMouseEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExerMouseEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExerMouseEvent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel coloredPnl;
    private javax.swing.JLabel displayLbl;
    // End of variables declaration//GEN-END:variables
}
